language: node_js
node_js:
  - "14.17.0"
env:
  - NODE_ENV=TEST
cache:
  yarn: true
  directories:
    - "node_modules"
services:
  - docker
before_script:
  - yarn install
script:
  - yarn test-ci || travis_terminate 1
  - yarn build || travis_terminate 1
